56

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -7,7 +7,9 @@ set -o pipefail dotglob nullglob failglob
 {
   cd -- "$(dirname -- "$0")/.."
   GIT_REPO="${GIT_REPO:-"$(basename -- "$PWD")"}"
-  GIT_TAG="$(git describe --tags --abbrev=0)"
+  if [[ -z ${CI:-""} ]]; then
+    GIT_TAG="$(git describe --tags --abbrev=0)"
+  fi
   VERSION="${GIT_TAG#v}"
   NAME_PREFIX="${GIT_REPO}_${VERSION}"
   MANIFEST="${NAME_PREFIX}_manifest.json"
@@ -16,13 +18,34 @@ set -o pipefail dotglob nullglob failglob
   SIGFILE="$SHAFILE.sig"
 }
 
+# Pipelines
+{
+  MAP=(xargs --no-run-if-empty -I % --)
+  LIST=(gh release list --limit 99999 --json 'tagName,isPrerelease' --jq '.[] | select(.isPrerelease).tagName')
+  FILTER=(gh release view --json 'tagName,.isPrerelease,assets' --jq 'if .isPrerelease and any(.assets[]; .name == "...") then .tagName else null end' --)
+  REMOVE=(gh release delete --yes -- %)
+}
+
 # Import GPG Key
 if [[ -n ${GPG_SIGNING_PASSWORD:-""} ]] && [[ -n ${GPG_SIGNING_KEY:-""} ]]; then
   printenv -- GPG_SIGNING_KEY | gpg --batch --passphrase-fd 3 --import 3<<< "$GPG_SIGNING_PASSWORD"
 elif [[ -n ${CI:-""} ]]; then
-  printf -- '%s\n' "GPG_SIGNING_PASSWORD, GPG_SIGNING_KEY must be set" >&2
+  tee -- <<- 'EOF' >&2
+GPG_SIGNING_PASSWORD, GPG_SIGNING_KEY must be set
+EOF
   exit 1
 fi
+
+# Smoke Test
+{
+  if [[ -n ${CI:-""} ]] && ! "${FILTER[@]}" "$GIT_TAG" | grep --fixed-string --quiet -- "$GIT_TAG"; then
+    tee -- <<- EOF >&2
+Release "$GIT_TAG" is not found in the list of pre-releases
+This might have happened because "$GIT_TAG" has been superseded by a later release
+EOF
+    exit 1
+  fi
+}
 
 # Build Artifacts
 {
@@ -52,4 +75,10 @@ fi
 if [[ -n ${CI:-""} ]]; then
   gh release upload --clobber -- "$GIT_TAG" "$DIST/$MANIFEST" "$SHAFILE" "$SIGFILE" "$DIST/"*.zip
   gh release edit --verify-tag --prerelease=false --latest -- "$GIT_TAG"
+
+fi
+
+# Clean Failed Releases
+if [[ -n ${CI:-""} ]]; then
+  "${LIST[@]}" | "${MAP[@]}" "${FILTER[@]}" % | awk -- '$0 { print }' | "${MAP[@]}" "${REMOVE[@]}"
 fi
